### PR TITLE
Mario Peña TidyVerse Assignment

### PR DESCRIPTION
**Pull request by marioipena**

### CODE REVIEW

**Comment by pnojai** [comment]
Mario,

This pull request has merge conflicts. 

Jai

**Comment by marioipena** [comment]
Hi Jai,

Thanks for volunteering to work on the pull requests for this assignment, you are greatly appreciated for your help.

I did a slight change to my Readme.md file but I am not sure if that is where the problem originated from. 

Please try merging my pull request again and let's see what happens.

Regards,
Mario

**Comment by pnojai** [comment]
Sorry, Mario. Still conflicts.

**Comment by marioipena** [comment]
I tried using other students' readme.md files as reference. I added a title and author to my file, but not sure if that will resolve the issue. If this doesn't work I will contact professor Catlin to let him know and ask for guidance.

Thank you Jai!

**Pull request merged**
