### PR TITLE
Add data607_tidyverse_Mengqin Cai

### PR DESCRIPTION
**Pull request by DaisyCai2019**
Upload two files. Data607_tidyverse_Mengqin Cai.md and  Data607_tidyverse_Mengqin Cai.Rmd.

### CODE REVIEW

**Comment by pnojai** [comment]
This pull request has merge conflicts.

**Comment by DaisyCai2019** [comment]
> This pull request has merge conflicts.
I don't need to do any update for readme.md but only want to upload the data607_tidyverse_Mengqin Cai.md and data607_tidyverse_Mengqin Cai.Rmd. Could you help me to resolve conflicting files and upload these two files? Or what should I do with those issues? I try to upload again but it still shows conflicts. Thanks. Jai.

**Comment by pnojai** [comment]
I can’t help you resolve merge conflicts. All I can do is click the button to merge the pull request when you have resolved your own conflicts.

Jai

**Comment by DaisyCai2019** [comment]
I solved the conflicts and may upload the files many times. Sorry about that.  Please help me to merge the pull request. Thanks. 

Mengqin Cai

**Pull request merged**
